- hosts: gns3
  become: true
  roles:
    - role: gns3
      vars:
        gns3_project_name: Trial_project
        switch_type: dellos10
        gns3_switch_model: "Dell OS10 S4000-10.5.6.13.327"
        gns3_cloud_interfaces:
        - cloud: Cloud1
          interface: breth1
          name: breth1
          port_number: 0
          type: ethernet
        - cloud: Cloud2
          interface: breth1
          name: breth1
          port_number: 0
          type: ethernet
        - cloud: Cloud3
          interface: brgns3
          name: brgns3
          port_number: 0
          type: ethernet
        gns3_switch_boot_delay: 181

        