---
gns3_project_name: "gns3_project"
gns3_work_dir: "{{ ansible_facts['env']['HOME'] }}/gns3-work"

gns3_links:
  - source_node: "{{ gns3_switch_model }}"
    source_adapter: 0
    source_port: 0
    target_node: Cloud
    target_adapter: 0
    target_port: 0

gns3_templates: []

# Configuration
management_ip: "192.168.33.10/24"
management_interface: "mgmt 1/1/1"