---
- name: Check if required nodes exist already
  gns3_node_status:
    project_name: "{{ gns3_project_name }}"
    node_type: "{{ gns3_switch_model }}"
  register: node_status

- name: Print node status
  ansible.builtin.debug:
    msg: "{{ node_status }}"

- name: Get node summary
  debug_node:
    project_name: "{{ gns3_project_name }}"
  register: node_summary

- name: Print node summary
  ansible.builtin.debug:
    msg: "{{ node_summary }}"

- name: Create Switch Node
  create_nodes:
    project_name: "{{ gns3_project_name }}"
    node_type: "{{ gns3_switch_model }}"
  when: not node_status.switch_node_present

- name: Create Required Cloud Nodes
  create_nodes:
    project_name: "{{ gns3_project_name }}"
    node_type: "Cloud"
    cloud_node_quantity: "{{ gns3_cloud_node_quantity }}"
    cloud_interfaces: "{{ gns3_cloud_interfaces }}"
  when: not node_status.cloud_node_present

- name: Start nodes
  gns3_start_nodes:
    project_name: "{{ gns3_project_name }}"