---
- name: Install Expect and Telnet packages
  ansible.builtin.apt:
    name:
      - expect
      - telnet
    state: present

- name: Get switch information
  gns3_node_info:
    project_name: "{{ gns3_project_name }}"
    node_name: "{{ gns3_switch_model }}"
  register: switch

- name: Print switch information
  ansible.builtin.debug:
    msg: "{{ switch }}"

- name: Wait until OS10 has finished booting
  ansible.builtin.command:
    argv:
      - expect
      - "{{ role_path }}/files/wait_for_login.exp"
      - "{{ switch.console_port }}"
  register: bootcheck
  retries: 120
  delay: 5
  until: bootcheck.rc == 0

- name: Give OS10 time to finish booting
  ansible.builtin.pause:
    seconds: "{{ gns3_switch_boot_delay | default(180) }}"

- name: Configure switch
  ansible.builtin.command:
    argv:
      - expect
      - "{{ role_path }}/files/set_admin_connection.exp"
      - "{{ switch.console_port }}"
      - "{{ management_interface }}"
      - "{{ management_ip }}"

# - name: Verify ping to switch -> doesnt work, needs variable set
#   ansible.netcommon.net_ping:
#     dest: "{{ management_ip }}"
#     count: 5
