---
- name: Install expect and telnet package
  ansible.builtin.apt:
    name:
      - expect
      - telnet
    state: present

- name: Get switch information
  gns3_node_info:
    project_name: "{{ gns3_project_name }}"
    node_name: "{{ gns3_node_type }}"
  register: switch

- name: Wait 10 minutes before configuring switch # would ideally change to polling
  ansible.builtin.pause:
    minutes: 10

- name: Wait for console
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ switch.console_port }}"

- name: Configure switch
  ansible.builtin.command:
    argv:
      - expect
      - "{{ role_path }}/files/expect_script.exp"
      - "{{ switch.console_port }}"
      - "{{ management_interface }}"
      - "{{ management_ip }}"
