---
- name: Install Expect and Telnet packages
  ansible.builtin.apt:
    name:
      - expect
      - telnet
    state: present

- name: Get switch information
  gns3_node_info:
    project_name: "{{ gns3_project_name }}"
    node_name: "{{ gns3_switch_type }}"
  register: switch

- name: Wait until OS10 has finished booting
  ansible.builtin.command:
    argv:
      - expect
      - "{{ role_path }}/files/wait_for_login.exp"
      - "{{ switch.console_port }}"
  register: bootcheck
  retries: 120
  delay: 10
  until: bootcheck.rc == 0

- name: Wait for console
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ switch.console_port }}"

- name: Configure switch
  ansible.builtin.command:
    argv:
      - expect
      - "{{ role_path }}/files/set_admin_connection.exp"
      - "{{ switch.console_port }}"
      - "{{ management_interface }}"
      - "{{ management_ip }}"
