---
- name: Gather Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure GNS3 work directory exists
  ansible.builtin.file:
    path: "{{ gns3_work_dir }}"
    state: directory

- name: Add GNS3 PPA
  ansible.builtin.apt_repository:
    repo: ppa:gns3/ppa
    state: present
    update_cache: true

- name: Install GNS3 packages
  ansible.builtin.apt:
    name:
      - gns3-server
    state: present
    update_cache: true

- name: Add i386 architecture
  ansible.builtin.shell: sudo dpkg --add-architecture i386
  args:
    executable: /bin/bash

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install GNS3 IOU
  ansible.builtin.apt:
    name:
      - gns3-iou
    state: present

- name: Add current user to required groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - ubridge
      - libvirt
      - kvm
      - wireshark
      - docker
      
- name: Launch GNS3 server (run gns3server)
  ansible.builtin.command:
    cmd: gns3server