---
- name: Gather Minimal Facts
  ansible.builtin.setup:
    gather_subset:
      - min

- name: Install GNS3 Server
  import_tasks: install_gns3.yml

- name: Create GNS3 Project
  import_tasks: create_project.yml

- name: Install GNS3 Templates
  import_tasks: install_templates.yml

- name: Upload GNS3 Templates
  import_tasks: upload_templates.yml

- name: Create GNS3 Nodes
  import_tasks: create_nodes.yml

- name: Create GNS3 Links
  import_tasks: create_links.yml